// models.proto contains shared message and enum definitions
// used by GophKeeper services.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gophkeeper/v1/models.proto

package gophkeeperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryType enumerates the kinds of private data
// an entry can hold.
type EntryType int32

const (
	// ENTRY_TYPE_UNSPECIFIED is the zero value and must not be used explicitly.
	EntryType_ENTRY_TYPE_UNSPECIFIED EntryType = 0
	// ENTRY_TYPE_LOGIN_PASSWORD is a login/password credential pair.
	EntryType_ENTRY_TYPE_LOGIN_PASSWORD EntryType = 1
	// ENTRY_TYPE_TEXT is an arbitrary text note.
	EntryType_ENTRY_TYPE_TEXT EntryType = 2
	// ENTRY_TYPE_BINARY is arbitrary binary data (e.g. a file).
	EntryType_ENTRY_TYPE_BINARY EntryType = 3
	// ENTRY_TYPE_CARD is bank card data.
	EntryType_ENTRY_TYPE_CARD EntryType = 4
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_UNSPECIFIED",
		1: "ENTRY_TYPE_LOGIN_PASSWORD",
		2: "ENTRY_TYPE_TEXT",
		3: "ENTRY_TYPE_BINARY",
		4: "ENTRY_TYPE_CARD",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_UNSPECIFIED":    0,
		"ENTRY_TYPE_LOGIN_PASSWORD": 1,
		"ENTRY_TYPE_TEXT":           2,
		"ENTRY_TYPE_BINARY":         3,
		"ENTRY_TYPE_CARD":           4,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_v1_models_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_gophkeeper_v1_models_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// User represents a registered GophKeeper account.
type User struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id        string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Login     string                 `protobuf:"bytes,2,opt,name=login,proto3"`
	xxx_hidden_CreatedAt int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_gophkeeper_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *User) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return 0
}

func (x *User) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *User) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *User) SetCreatedAt(v int64) {
	x.xxx_hidden_CreatedAt = v
}

type User_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// id is the unique server-assigned user identifier.
	Id string
	// login is the unique login name used for authentication.
	Login string
	// created_at is the account creation timestamp, Unix seconds (UTC).
	CreatedAt int64
}

func (b0 User_builder) Build() *User {
	m0 := &User{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_CreatedAt = b.CreatedAt
	return m0
}

// Entry is a single piece of the user's private data stored on the server.
// The actual payload is carried in the data field as bytes; its meaning
// is determined by type.
type Entry struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id        string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Type      EntryType              `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.v1.EntryType"`
	xxx_hidden_Label     string                 `protobuf:"bytes,3,opt,name=label,proto3"`
	xxx_hidden_Metadata  string                 `protobuf:"bytes,4,opt,name=metadata,proto3"`
	xxx_hidden_Data      []byte                 `protobuf:"bytes,5,opt,name=data,proto3"`
	xxx_hidden_Version   int64                  `protobuf:"varint,6,opt,name=version,proto3"`
	xxx_hidden_CreatedAt int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3"`
	xxx_hidden_UpdatedAt int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3"`
	xxx_hidden_DataSize  int64                  `protobuf:"varint,9,opt,name=data_size,json=dataSize,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_gophkeeper_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *Entry) GetType() EntryType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return EntryType_ENTRY_TYPE_UNSPECIFIED
}

func (x *Entry) GetLabel() string {
	if x != nil {
		return x.xxx_hidden_Label
	}
	return ""
}

func (x *Entry) GetMetadata() string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return ""
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Entry) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Entry) GetCreatedAt() int64 {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return 0
}

func (x *Entry) GetUpdatedAt() int64 {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return 0
}

func (x *Entry) GetDataSize() int64 {
	if x != nil {
		return x.xxx_hidden_DataSize
	}
	return 0
}

func (x *Entry) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *Entry) SetType(v EntryType) {
	x.xxx_hidden_Type = v
}

func (x *Entry) SetLabel(v string) {
	x.xxx_hidden_Label = v
}

func (x *Entry) SetMetadata(v string) {
	x.xxx_hidden_Metadata = v
}

func (x *Entry) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
}

func (x *Entry) SetVersion(v int64) {
	x.xxx_hidden_Version = v
}

func (x *Entry) SetCreatedAt(v int64) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Entry) SetUpdatedAt(v int64) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Entry) SetDataSize(v int64) {
	x.xxx_hidden_DataSize = v
}

type Entry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// id is the unique server-assigned entry identifier.
	Id string
	// type defines how the data field should be interpreted.
	Type EntryType
	// label is a user-visible name of the entry.
	Label string
	// metadata holds arbitrary text metadata supplied by the user.
	Metadata string
	// data is the entry payload:
	// LOGIN_PASSWORD — serialized credential pair,
	// TEXT — UTF-8 text,
	// BINARY — raw bytes,
	// CARD — serialized card data.
	Data []byte
	// version is incremented on every update and used for optimistic locking:
	// update requests must carry the version they are based on.
	Version int64
	// created_at is the entry creation timestamp, Unix seconds (UTC).
	CreatedAt int64
	// updated_at is the last modification timestamp, Unix seconds (UTC).
	UpdatedAt int64
	// data_size is the server-reported size of the entry payload in bytes.
	// It is populated even when data itself is omitted (see
	// ListEntriesRequest.include_data and SyncRequest.include_data), so
	// clients can show sizes and decide whether to download the content.
	DataSize int64
}

func (b0 Entry_builder) Build() *Entry {
	m0 := &Entry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Label = b.Label
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_Version = b.Version
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_DataSize = b.DataSize
	return m0
}

var File_gophkeeper_v1_models_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x1agophkeeper/v1/models.proto\x12\rgophkeeper.v1\"K\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"\x80\x02\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.gophkeeper.v1.EntryTypeR\x04type\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x12\x1b\n" +
	"\tdata_size\x18\t \x01(\x03R\bdataSize*\x87\x01\n" +
	"\tEntryType\x12\x1a\n" +
	"\x16ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ENTRY_TYPE_LOGIN_PASSWORD\x10\x01\x12\x13\n" +
	"\x0fENTRY_TYPE_TEXT\x10\x02\x12\x15\n" +
	"\x11ENTRY_TYPE_BINARY\x10\x03\x12\x13\n" +
	"\x0fENTRY_TYPE_CARD\x10\x04BOZMgithub.com/dmitriy/gophkeeper/internal/common/proto/gophkeeperv1;gophkeeperv1b\x06proto3"

var file_gophkeeper_v1_models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gophkeeper_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gophkeeper_v1_models_proto_goTypes = []any{
	(EntryType)(0), // 0: gophkeeper.v1.EntryType
	(*User)(nil),   // 1: gophkeeper.v1.User
	(*Entry)(nil),  // 2: gophkeeper.v1.Entry
}
var file_gophkeeper_v1_models_proto_depIdxs = []int32{
	0, // 0: gophkeeper.v1.Entry.type:type_name -> gophkeeper.v1.EntryType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_models_proto_init() }
func file_gophkeeper_v1_models_proto_init() {
	if File_gophkeeper_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_models_proto_rawDesc), len(file_gophkeeper_v1_models_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gophkeeper_v1_models_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_models_proto_depIdxs,
		EnumInfos:         file_gophkeeper_v1_models_proto_enumTypes,
		MessageInfos:      file_gophkeeper_v1_models_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_models_proto = out.File
	file_gophkeeper_v1_models_proto_goTypes = nil
	file_gophkeeper_v1_models_proto_depIdxs = nil
}
