// models.proto contains shared message and enum definitions
// used by GophKeeper services.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gophkeeper/v1/models.proto

package gophkeeperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryType enumerates the kinds of private data
// an entry can hold.
type EntryType int32

const (
	// ENTRY_TYPE_UNSPECIFIED is the zero value and must not be used explicitly.
	EntryType_ENTRY_TYPE_UNSPECIFIED EntryType = 0
	// ENTRY_TYPE_LOGIN_PASSWORD is a login/password credential pair.
	EntryType_ENTRY_TYPE_LOGIN_PASSWORD EntryType = 1
	// ENTRY_TYPE_TEXT is an arbitrary text note.
	EntryType_ENTRY_TYPE_TEXT EntryType = 2
	// ENTRY_TYPE_BINARY is arbitrary binary data (e.g. a file).
	EntryType_ENTRY_TYPE_BINARY EntryType = 3
	// ENTRY_TYPE_CARD is bank card data.
	EntryType_ENTRY_TYPE_CARD EntryType = 4
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_UNSPECIFIED",
		1: "ENTRY_TYPE_LOGIN_PASSWORD",
		2: "ENTRY_TYPE_TEXT",
		3: "ENTRY_TYPE_BINARY",
		4: "ENTRY_TYPE_CARD",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_UNSPECIFIED":    0,
		"ENTRY_TYPE_LOGIN_PASSWORD": 1,
		"ENTRY_TYPE_TEXT":           2,
		"ENTRY_TYPE_BINARY":         3,
		"ENTRY_TYPE_CARD":           4,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_v1_models_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_gophkeeper_v1_models_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_v1_models_proto_rawDescGZIP(), []int{0}
}

// User represents a registered GophKeeper account.
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique server-assigned user identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// login is the unique login name used for authentication.
	Login string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	// created_at is the account creation timestamp, Unix seconds (UTC).
	CreatedAt     int64 `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_gophkeeper_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Entry is a single piece of the user's private data stored on the server.
// The actual payload is carried in the data field as bytes; its meaning
// is determined by type.
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique server-assigned entry identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// type defines how the data field should be interpreted.
	Type EntryType `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeper.v1.EntryType" json:"type,omitempty"`
	// label is a user-visible name of the entry.
	Label string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	// metadata holds arbitrary text metadata supplied by the user.
	Metadata string `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// data is the entry payload:
	// LOGIN_PASSWORD — serialized credential pair,
	// TEXT — UTF-8 text,
	// BINARY — raw bytes,
	// CARD — serialized card data.
	Data []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	// version is incremented on every update and used for optimistic locking:
	// update requests must carry the version they are based on.
	Version int64 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	// created_at is the entry creation timestamp, Unix seconds (UTC).
	CreatedAt int64 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at is the last modification timestamp, Unix seconds (UTC).
	UpdatedAt     int64 `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_gophkeeper_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_ENTRY_TYPE_UNSPECIFIED
}

func (x *Entry) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Entry) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Entry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Entry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Entry) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_gophkeeper_v1_models_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x1agophkeeper/v1/models.proto\x12\rgophkeeper.v1\"K\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"\xe3\x01\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.gophkeeper.v1.EntryTypeR\x04type\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt*\x87\x01\n" +
	"\tEntryType\x12\x1a\n" +
	"\x16ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ENTRY_TYPE_LOGIN_PASSWORD\x10\x01\x12\x13\n" +
	"\x0fENTRY_TYPE_TEXT\x10\x02\x12\x15\n" +
	"\x11ENTRY_TYPE_BINARY\x10\x03\x12\x13\n" +
	"\x0fENTRY_TYPE_CARD\x10\x04BOZMgithub.com/dmitriy/gophkeeper/internal/common/proto/gophkeeperv1;gophkeeperv1b\x06proto3"

var (
	file_gophkeeper_v1_models_proto_rawDescOnce sync.Once
	file_gophkeeper_v1_models_proto_rawDescData []byte
)

func file_gophkeeper_v1_models_proto_rawDescGZIP() []byte {
	file_gophkeeper_v1_models_proto_rawDescOnce.Do(func() {
		file_gophkeeper_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_models_proto_rawDesc), len(file_gophkeeper_v1_models_proto_rawDesc)))
	})
	return file_gophkeeper_v1_models_proto_rawDescData
}

var file_gophkeeper_v1_models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gophkeeper_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gophkeeper_v1_models_proto_goTypes = []any{
	(EntryType)(0), // 0: gophkeeper.v1.EntryType
	(*User)(nil),   // 1: gophkeeper.v1.User
	(*Entry)(nil),  // 2: gophkeeper.v1.Entry
}
var file_gophkeeper_v1_models_proto_depIdxs = []int32{
	0, // 0: gophkeeper.v1.Entry.type:type_name -> gophkeeper.v1.EntryType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_models_proto_init() }
func file_gophkeeper_v1_models_proto_init() {
	if File_gophkeeper_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_models_proto_rawDesc), len(file_gophkeeper_v1_models_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gophkeeper_v1_models_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_models_proto_depIdxs,
		EnumInfos:         file_gophkeeper_v1_models_proto_enumTypes,
		MessageInfos:      file_gophkeeper_v1_models_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_models_proto = out.File
	file_gophkeeper_v1_models_proto_goTypes = nil
	file_gophkeeper_v1_models_proto_depIdxs = nil
}
