// service.proto defines the private-data entry management API of GophKeeper.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gophkeeper/v1/service.proto

package gophkeeperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateEntryRequest contains the entry to store for the authenticated user.
type CreateEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entry holds the type, label, metadata and data to store.
	// id, version and timestamps are ignored by the server.
	Entry         *Entry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntryRequest) Reset() {
	*x = CreateEntryRequest{}
	mi := &file_gophkeeper_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntryRequest) ProtoMessage() {}

func (x *CreateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntryRequest.ProtoReflect.Descriptor instead.
func (*CreateEntryRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEntryRequest) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// CreateEntryResponse returns the stored entry as seen by the server.
type CreateEntryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entry includes the server-assigned id, version and timestamps.
	Entry         *Entry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntryResponse) Reset() {
	*x = CreateEntryResponse{}
	mi := &file_gophkeeper_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntryResponse) ProtoMessage() {}

func (x *CreateEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntryResponse.ProtoReflect.Descriptor instead.
func (*CreateEntryResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEntryResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// GetEntryRequest identifies an entry to fetch.
type GetEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the entry identifier.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryRequest) Reset() {
	*x = GetEntryRequest{}
	mi := &file_gophkeeper_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryRequest) ProtoMessage() {}

func (x *GetEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryRequest.ProtoReflect.Descriptor instead.
func (*GetEntryRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetEntryResponse returns the requested entry.
type GetEntryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entry is the stored entry with all fields populated.
	Entry         *Entry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryResponse) Reset() {
	*x = GetEntryResponse{}
	mi := &file_gophkeeper_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryResponse) ProtoMessage() {}

func (x *GetEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryResponse.ProtoReflect.Descriptor instead.
func (*GetEntryResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetEntryResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// ListEntriesRequest asks for all entries of the authenticated user.
type ListEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_gophkeeper_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_service_proto_rawDescGZIP(), []int{4}
}

// ListEntriesResponse returns all entries of the user.
type ListEntriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entries are the user's entries in unspecified order.
	Entries       []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_gophkeeper_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListEntriesResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// UpdateEntryRequest contains the new entry state for optimistic locking.
type UpdateEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entry must carry the existing id, label/metadata/data changes
	// and the version the update is based on.
	Entry         *Entry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntryRequest) Reset() {
	*x = UpdateEntryRequest{}
	mi := &file_gophkeeper_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntryRequest) ProtoMessage() {}

func (x *UpdateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntryRequest.ProtoReflect.Descriptor instead.
func (*UpdateEntryRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEntryRequest) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// UpdateEntryResponse returns the updated entry with a bumped version.
type UpdateEntryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entry is the entry after the update.
	Entry         *Entry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEntryResponse) Reset() {
	*x = UpdateEntryResponse{}
	mi := &file_gophkeeper_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEntryResponse) ProtoMessage() {}

func (x *UpdateEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEntryResponse.ProtoReflect.Descriptor instead.
func (*UpdateEntryResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateEntryResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// DeleteEntryRequest identifies an entry to remove.
type DeleteEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the entry identifier.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntryRequest) Reset() {
	*x = DeleteEntryRequest{}
	mi := &file_gophkeeper_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryRequest) ProtoMessage() {}

func (x *DeleteEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntryRequest.ProtoReflect.Descriptor instead.
func (*DeleteEntryRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEntryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteEntryResponse confirms the deletion.
type DeleteEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntryResponse) Reset() {
	*x = DeleteEntryResponse{}
	mi := &file_gophkeeper_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryResponse) ProtoMessage() {}

func (x *DeleteEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntryResponse.ProtoReflect.Descriptor instead.
func (*DeleteEntryResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_service_proto_rawDescGZIP(), []int{9}
}

// SyncRequest asks for the current state of all entries of the
// authenticated user.
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_gophkeeper_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_service_proto_rawDescGZIP(), []int{10}
}

// SyncResponse carries the full current list of the user's entries,
// so multiple authorized clients of the same owner stay in sync.
type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entries is the complete current set of the user's entries.
	Entries       []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_gophkeeper_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *SyncResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_gophkeeper_v1_service_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bgophkeeper/v1/service.proto\x12\rgophkeeper.v1\x1a\x1agophkeeper/v1/models.proto\"@\n" +
	"\x12CreateEntryRequest\x12*\n" +
	"\x05entry\x18\x01 \x01(\v2\x14.gophkeeper.v1.EntryR\x05entry\"A\n" +
	"\x13CreateEntryResponse\x12*\n" +
	"\x05entry\x18\x01 \x01(\v2\x14.gophkeeper.v1.EntryR\x05entry\"!\n" +
	"\x0fGetEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x10GetEntryResponse\x12*\n" +
	"\x05entry\x18\x01 \x01(\v2\x14.gophkeeper.v1.EntryR\x05entry\"\x14\n" +
	"\x12ListEntriesRequest\"E\n" +
	"\x13ListEntriesResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.gophkeeper.v1.EntryR\aentries\"@\n" +
	"\x12UpdateEntryRequest\x12*\n" +
	"\x05entry\x18\x01 \x01(\v2\x14.gophkeeper.v1.EntryR\x05entry\"A\n" +
	"\x13UpdateEntryResponse\x12*\n" +
	"\x05entry\x18\x01 \x01(\v2\x14.gophkeeper.v1.EntryR\x05entry\"$\n" +
	"\x12DeleteEntryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteEntryResponse\"\r\n" +
	"\vSyncRequest\">\n" +
	"\fSyncResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.gophkeeper.v1.EntryR\aentries2\xd9\x03\n" +
	"\fEntryService\x12O\n" +
	"\x06Create\x12!.gophkeeper.v1.CreateEntryRequest\x1a\".gophkeeper.v1.CreateEntryResponse\x12F\n" +
	"\x03Get\x12\x1e.gophkeeper.v1.GetEntryRequest\x1a\x1f.gophkeeper.v1.GetEntryResponse\x12M\n" +
	"\x04List\x12!.gophkeeper.v1.ListEntriesRequest\x1a\".gophkeeper.v1.ListEntriesResponse\x12O\n" +
	"\x06Update\x12!.gophkeeper.v1.UpdateEntryRequest\x1a\".gophkeeper.v1.UpdateEntryResponse\x12O\n" +
	"\x06Delete\x12!.gophkeeper.v1.DeleteEntryRequest\x1a\".gophkeeper.v1.DeleteEntryResponse\x12?\n" +
	"\x04Sync\x12\x1a.gophkeeper.v1.SyncRequest\x1a\x1b.gophkeeper.v1.SyncResponseBOZMgithub.com/dmitriy/gophkeeper/internal/common/proto/gophkeeperv1;gophkeeperv1b\x06proto3"

var (
	file_gophkeeper_v1_service_proto_rawDescOnce sync.Once
	file_gophkeeper_v1_service_proto_rawDescData []byte
)

func file_gophkeeper_v1_service_proto_rawDescGZIP() []byte {
	file_gophkeeper_v1_service_proto_rawDescOnce.Do(func() {
		file_gophkeeper_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_service_proto_rawDesc), len(file_gophkeeper_v1_service_proto_rawDesc)))
	})
	return file_gophkeeper_v1_service_proto_rawDescData
}

var file_gophkeeper_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gophkeeper_v1_service_proto_goTypes = []any{
	(*CreateEntryRequest)(nil),  // 0: gophkeeper.v1.CreateEntryRequest
	(*CreateEntryResponse)(nil), // 1: gophkeeper.v1.CreateEntryResponse
	(*GetEntryRequest)(nil),     // 2: gophkeeper.v1.GetEntryRequest
	(*GetEntryResponse)(nil),    // 3: gophkeeper.v1.GetEntryResponse
	(*ListEntriesRequest)(nil),  // 4: gophkeeper.v1.ListEntriesRequest
	(*ListEntriesResponse)(nil), // 5: gophkeeper.v1.ListEntriesResponse
	(*UpdateEntryRequest)(nil),  // 6: gophkeeper.v1.UpdateEntryRequest
	(*UpdateEntryResponse)(nil), // 7: gophkeeper.v1.UpdateEntryResponse
	(*DeleteEntryRequest)(nil),  // 8: gophkeeper.v1.DeleteEntryRequest
	(*DeleteEntryResponse)(nil), // 9: gophkeeper.v1.DeleteEntryResponse
	(*SyncRequest)(nil),         // 10: gophkeeper.v1.SyncRequest
	(*SyncResponse)(nil),        // 11: gophkeeper.v1.SyncResponse
	(*Entry)(nil),               // 12: gophkeeper.v1.Entry
}
var file_gophkeeper_v1_service_proto_depIdxs = []int32{
	12, // 0: gophkeeper.v1.CreateEntryRequest.entry:type_name -> gophkeeper.v1.Entry
	12, // 1: gophkeeper.v1.CreateEntryResponse.entry:type_name -> gophkeeper.v1.Entry
	12, // 2: gophkeeper.v1.GetEntryResponse.entry:type_name -> gophkeeper.v1.Entry
	12, // 3: gophkeeper.v1.ListEntriesResponse.entries:type_name -> gophkeeper.v1.Entry
	12, // 4: gophkeeper.v1.UpdateEntryRequest.entry:type_name -> gophkeeper.v1.Entry
	12, // 5: gophkeeper.v1.UpdateEntryResponse.entry:type_name -> gophkeeper.v1.Entry
	12, // 6: gophkeeper.v1.SyncResponse.entries:type_name -> gophkeeper.v1.Entry
	0,  // 7: gophkeeper.v1.EntryService.Create:input_type -> gophkeeper.v1.CreateEntryRequest
	2,  // 8: gophkeeper.v1.EntryService.Get:input_type -> gophkeeper.v1.GetEntryRequest
	4,  // 9: gophkeeper.v1.EntryService.List:input_type -> gophkeeper.v1.ListEntriesRequest
	6,  // 10: gophkeeper.v1.EntryService.Update:input_type -> gophkeeper.v1.UpdateEntryRequest
	8,  // 11: gophkeeper.v1.EntryService.Delete:input_type -> gophkeeper.v1.DeleteEntryRequest
	10, // 12: gophkeeper.v1.EntryService.Sync:input_type -> gophkeeper.v1.SyncRequest
	1,  // 13: gophkeeper.v1.EntryService.Create:output_type -> gophkeeper.v1.CreateEntryResponse
	3,  // 14: gophkeeper.v1.EntryService.Get:output_type -> gophkeeper.v1.GetEntryResponse
	5,  // 15: gophkeeper.v1.EntryService.List:output_type -> gophkeeper.v1.ListEntriesResponse
	7,  // 16: gophkeeper.v1.EntryService.Update:output_type -> gophkeeper.v1.UpdateEntryResponse
	9,  // 17: gophkeeper.v1.EntryService.Delete:output_type -> gophkeeper.v1.DeleteEntryResponse
	11, // 18: gophkeeper.v1.EntryService.Sync:output_type -> gophkeeper.v1.SyncResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_service_proto_init() }
func file_gophkeeper_v1_service_proto_init() {
	if File_gophkeeper_v1_service_proto != nil {
		return
	}
	file_gophkeeper_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_service_proto_rawDesc), len(file_gophkeeper_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_v1_service_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_service_proto_depIdxs,
		MessageInfos:      file_gophkeeper_v1_service_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_service_proto = out.File
	file_gophkeeper_v1_service_proto_goTypes = nil
	file_gophkeeper_v1_service_proto_depIdxs = nil
}
