// service.proto defines the private-data entry management API of GophKeeper.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: gophkeeper/v1/service.proto

package gophkeeperv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntryService_Create_FullMethodName            = "/gophkeeper.v1.EntryService/Create"
	EntryService_Get_FullMethodName               = "/gophkeeper.v1.EntryService/Get"
	EntryService_List_FullMethodName              = "/gophkeeper.v1.EntryService/List"
	EntryService_Update_FullMethodName            = "/gophkeeper.v1.EntryService/Update"
	EntryService_Delete_FullMethodName            = "/gophkeeper.v1.EntryService/Delete"
	EntryService_Sync_FullMethodName              = "/gophkeeper.v1.EntryService/Sync"
	EntryService_Upload_FullMethodName            = "/gophkeeper.v1.EntryService/Upload"
	EntryService_DownloadEntryData_FullMethodName = "/gophkeeper.v1.EntryService/DownloadEntryData"
)

// EntryServiceClient is the client API for EntryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EntryService manages the authenticated user's private data entries.
type EntryServiceClient interface {
	// Create stores a new entry for the authenticated user.
	Create(ctx context.Context, in *CreateEntryRequest, opts ...grpc.CallOption) (*CreateEntryResponse, error)
	// Get returns a single entry by id.
	Get(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error)
	// List returns all entries of the authenticated user.
	List(ctx context.Context, in *ListEntriesRequest, opts ...grpc.CallOption) (*ListEntriesResponse, error)
	// Update replaces an entry's content; fails if version is stale.
	Update(ctx context.Context, in *UpdateEntryRequest, opts ...grpc.CallOption) (*UpdateEntryResponse, error)
	// Delete removes an entry by id.
	Delete(ctx context.Context, in *DeleteEntryRequest, opts ...grpc.CallOption) (*DeleteEntryResponse, error)
	// Sync returns the full current list of the authenticated user's entries,
	// allowing several authorized clients of the same owner to converge
	// on the same server state.
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Upload stores an entry streamed as chunks (client-streaming):
	// the first message is an UploadEntryHeader, the rest are payload
	// chunks. It supports both creating a new entry (expected_version 0)
	// and replacing the payload of an existing one guarded by
	// optimistic locking. The whole upload is atomic: the entry becomes
	// visible only after the stream completes successfully.
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadEntryRequest, UploadEntryResponse], error)
	// DownloadEntryData streams the payload of a single entry
	// (server-streaming): the first message is a header with the total
	// size, the rest are payload chunks.
	DownloadEntryData(ctx context.Context, in *DownloadEntryDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadEntryDataResponse], error)
}

type entryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEntryServiceClient(cc grpc.ClientConnInterface) EntryServiceClient {
	return &entryServiceClient{cc}
}

func (c *entryServiceClient) Create(ctx context.Context, in *CreateEntryRequest, opts ...grpc.CallOption) (*CreateEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEntryResponse)
	err := c.cc.Invoke(ctx, EntryService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryServiceClient) Get(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntryResponse)
	err := c.cc.Invoke(ctx, EntryService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryServiceClient) List(ctx context.Context, in *ListEntriesRequest, opts ...grpc.CallOption) (*ListEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEntriesResponse)
	err := c.cc.Invoke(ctx, EntryService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryServiceClient) Update(ctx context.Context, in *UpdateEntryRequest, opts ...grpc.CallOption) (*UpdateEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEntryResponse)
	err := c.cc.Invoke(ctx, EntryService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryServiceClient) Delete(ctx context.Context, in *DeleteEntryRequest, opts ...grpc.CallOption) (*DeleteEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEntryResponse)
	err := c.cc.Invoke(ctx, EntryService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryServiceClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, EntryService_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entryServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadEntryRequest, UploadEntryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EntryService_ServiceDesc.Streams[0], EntryService_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadEntryRequest, UploadEntryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EntryService_UploadClient = grpc.ClientStreamingClient[UploadEntryRequest, UploadEntryResponse]

func (c *entryServiceClient) DownloadEntryData(ctx context.Context, in *DownloadEntryDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadEntryDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EntryService_ServiceDesc.Streams[1], EntryService_DownloadEntryData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadEntryDataRequest, DownloadEntryDataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EntryService_DownloadEntryDataClient = grpc.ServerStreamingClient[DownloadEntryDataResponse]

// EntryServiceServer is the server API for EntryService service.
// All implementations must embed UnimplementedEntryServiceServer
// for forward compatibility.
//
// EntryService manages the authenticated user's private data entries.
type EntryServiceServer interface {
	// Create stores a new entry for the authenticated user.
	Create(context.Context, *CreateEntryRequest) (*CreateEntryResponse, error)
	// Get returns a single entry by id.
	Get(context.Context, *GetEntryRequest) (*GetEntryResponse, error)
	// List returns all entries of the authenticated user.
	List(context.Context, *ListEntriesRequest) (*ListEntriesResponse, error)
	// Update replaces an entry's content; fails if version is stale.
	Update(context.Context, *UpdateEntryRequest) (*UpdateEntryResponse, error)
	// Delete removes an entry by id.
	Delete(context.Context, *DeleteEntryRequest) (*DeleteEntryResponse, error)
	// Sync returns the full current list of the authenticated user's entries,
	// allowing several authorized clients of the same owner to converge
	// on the same server state.
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
	// Upload stores an entry streamed as chunks (client-streaming):
	// the first message is an UploadEntryHeader, the rest are payload
	// chunks. It supports both creating a new entry (expected_version 0)
	// and replacing the payload of an existing one guarded by
	// optimistic locking. The whole upload is atomic: the entry becomes
	// visible only after the stream completes successfully.
	Upload(grpc.ClientStreamingServer[UploadEntryRequest, UploadEntryResponse]) error
	// DownloadEntryData streams the payload of a single entry
	// (server-streaming): the first message is a header with the total
	// size, the rest are payload chunks.
	DownloadEntryData(*DownloadEntryDataRequest, grpc.ServerStreamingServer[DownloadEntryDataResponse]) error
	mustEmbedUnimplementedEntryServiceServer()
}

// UnimplementedEntryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntryServiceServer struct{}

func (UnimplementedEntryServiceServer) Create(context.Context, *CreateEntryRequest) (*CreateEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedEntryServiceServer) Get(context.Context, *GetEntryRequest) (*GetEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedEntryServiceServer) List(context.Context, *ListEntriesRequest) (*ListEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedEntryServiceServer) Update(context.Context, *UpdateEntryRequest) (*UpdateEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedEntryServiceServer) Delete(context.Context, *DeleteEntryRequest) (*DeleteEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedEntryServiceServer) Sync(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedEntryServiceServer) Upload(grpc.ClientStreamingServer[UploadEntryRequest, UploadEntryResponse]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedEntryServiceServer) DownloadEntryData(*DownloadEntryDataRequest, grpc.ServerStreamingServer[DownloadEntryDataResponse]) error {
	return status.Error(codes.Unimplemented, "method DownloadEntryData not implemented")
}
func (UnimplementedEntryServiceServer) mustEmbedUnimplementedEntryServiceServer() {}
func (UnimplementedEntryServiceServer) testEmbeddedByValue()                      {}

// UnsafeEntryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntryServiceServer will
// result in compilation errors.
type UnsafeEntryServiceServer interface {
	mustEmbedUnimplementedEntryServiceServer()
}

func RegisterEntryServiceServer(s grpc.ServiceRegistrar, srv EntryServiceServer) {
	// If the following call panics, it indicates UnimplementedEntryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntryService_ServiceDesc, srv)
}

func _EntryService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntryService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryServiceServer).Create(ctx, req.(*CreateEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntryService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryServiceServer).Get(ctx, req.(*GetEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntryService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryServiceServer).List(ctx, req.(*ListEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntryService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryServiceServer).Update(ctx, req.(*UpdateEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntryService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryServiceServer).Delete(ctx, req.(*DeleteEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntryService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryServiceServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntryService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EntryServiceServer).Upload(&grpc.GenericServerStream[UploadEntryRequest, UploadEntryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EntryService_UploadServer = grpc.ClientStreamingServer[UploadEntryRequest, UploadEntryResponse]

func _EntryService_DownloadEntryData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadEntryDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EntryServiceServer).DownloadEntryData(m, &grpc.GenericServerStream[DownloadEntryDataRequest, DownloadEntryDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EntryService_DownloadEntryDataServer = grpc.ServerStreamingServer[DownloadEntryDataResponse]

// EntryService_ServiceDesc is the grpc.ServiceDesc for EntryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gophkeeper.v1.EntryService",
	HandlerType: (*EntryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _EntryService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _EntryService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _EntryService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _EntryService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _EntryService_Delete_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _EntryService_Sync_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _EntryService_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadEntryData",
			Handler:       _EntryService_DownloadEntryData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gophkeeper/v1/service.proto",
}
